name: LilyPad-Portal
version: ${build.number}
description: LilyPad

author: LilyPad
website: http://www.lilypadmc.org/

main: ${main.class}
depend: [LilyPad-Connect]

commands:
  portal:
    description:
    usage:
